language: node_js
node_js:
  - "9"
services:
    - mysql
env:
    - NODE_ENV=test
before_install:
    - "cd api && npm install -s"
    - mysql -e 'CREATE DATABASE contactsDbTest;'
script:
    - cd api && npm test