version: "3"
services: 
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
       - ./database:/docker-entrypoint-initdb.d
       - db-data:/var/lib/mysql/data
    ports:
      - 3306:3306

volumes:
  db-data: